### ISSUE TITLE
Wrong typography

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/df-web#116]
The current app visible under https://df.oceandao.org uses [IBM's corporate branding typeface](https://www.ibm.com/plex/) for whatever reason. Besides the fact we really don't want to be associated with that company, this app should follow [Ocean's brand guidelines](https://oceanprotocol.com/art#styleguide).

<img width="979" alt="Screen Shot 2022-06-16 at 16 14 40" src="https://user-images.githubusercontent.com/90316/174102776-316fbfb7-d621-4b55-aacd-a114ba42d3eb.png">

As this app is created by members of the oceanprotocol org, you can access this:
https://github.com/oceanprotocol/typographies

Instructions are in the above readme, increases app size a bit but you don't have to move over any font files, they are all delivered with `@import` in css so no licensing issues by making this repo here public with a copyrighted font.

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/116?planning-poker) with Zenhub @KatunaNorbert

**Comment by idiom-bytes** [comment]
This task ballooned in size due to loose requirements.

Let's please make sure to break tasks down into smaller deliverables, and if complications arise let's triage them and decide whether we complete the whole thing, or deliver just what's required.

Based on where it is, it should take less than 1/2 a day to complete.

**Comment by idiom-bytes** [comment]
This task ballooned in size due to loose requirements.

Let's please make sure to break tasks down into smaller deliverables, and if complications arise let's triage them and decide whether we complete the whole thing, or deliver just what's required.

Based on where it is, it should take less than 1/2 a day to complete.
