### ISSUE TITLE
Inform user about new changes and enable cache clearing 

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#135]
We should inform the user about new changes and give them an easy way to clear cache in order to see the latest changes

**Comment by trentmc** [comment]
Could you elaborate on this issue please. E.g. What does "new changes" mean?

**Comment by KatunaNorbert** [comment]
When we add anything new to the webpage and then we deploy the changes, those are not visible right away because of cached information. 
We could have a mecanism similar to what we have inside the oceanprotocol site which shows you a popup with a message and a refresh button, then once you click the bottom the cached information is cleared, page is reloaded and you see the up to date page.

**Comment by kremalicious** [comment]
this only works on the main site, or more precisely we absolutely have to provide a manual refresh button, because it uses a service worker which makes the site available offline. Without a service worker you have no way of detecting when an update occurred, and your users still have the old files in their browser caches. So unless this app is planning on using a service worker, this issue is unsolvable.

As on market, which does not use any service worker, invalidating caches is done without any user interaction with cache busting: each asset gets a hashed file name based on its content. If asset content changes, hash changes, making user download new file regardless of cache if the initiating file (the index.html file) is not cached.

Pretty much every site building framework provides this out of the box, like Gate sy, Next.js, SvelteKit. Otherwise this has to be directed in whatever build process is setup, in webpack, Svelte, Rollup etc.
