### ISSUE TITLE
Create admin/debug page to make it easy for anyone to debug what's going on

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#355]
We may want to consider putting this together to make it dead easy to debug issues... Otherwise, with ever ticket, we have to adjust code, run locally/etc, and start from there. By having a debug/admin panel, it might make it easier to assess each ticket, and facilitate the work between community managers and the dev team.

Create admin panel:
- User can add any address
- User can see: ocean balance, veocean balance, active rewards, passive rewards, etc...
- If there is a discrepancy between this and the FE, then we have a bug

**Comment by idiom-bytes** [comment]
However, this is diminishing returns as we harden the app. If continue having to debug a lot of issues, then consider implementing something like this.

**Comment by idiom-bytes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VE--DF-60ddbf267dd0b500137f3c3d/issues/oceanprotocol/df-web/355?planning-poker) with Zenhub @KatunaNorbert

**Comment by idiom-bytes** [comment]
The problem with this implementation Norbert is that it doesn't serve prod.

I.E. We need something that enables a community manager to debug something in mainnet.
Although unorthodox, I like the current implementation.
I'm not sure what others thing. Have you asked them to review it?

Finally, i think the address should remain semi-obscured i.e. `0x1111...zzzz`.

**Comment by KatunaNorbert** [comment]
@idiom-bytes you are right, this will only work on staging/development, but this was intended because I don't know If we want to make this enabled for all users in production, If so, we need to spend more time on it and make it more user friendly.

But I see an issue that you have pointed, which is that staging is running on test network, so how do we debug mainnet?

I could add a component to also choose the network you want to debug. This way we can debug mainnet from staging.
