### ISSUE TITLE
Improve asset total allocations display

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#388]
The current TotalAllocated column contains the sampled allocation, which means that if user moves his allocations from asset A to asset B, this will happen gradually due to the sampling process, and the entire allocations will be moved over only at the beginning of the next round. 
Problem is that users expect to see the allocations moved over to the new asset right away, or as soon as possible.

This creates confusion for the users, although this is exactly what it's going on in the perspective of rewards calculation and it's not an issue.
To make this more clear, create 2 separate table column as following:
1.Rename the current column which contains the sampled total allocations and add more information inside a tooltip.
2.Add a new column which contains the not sampled total allocation. This will confirm the user that his allocation have moved to the new asset and users can also have a better overview of where the allocations are without having to wait until the round has ended.

**Comment by graceful-coder** [comment]
I reviewed the UI for this fix in Staging with Norbert today. We decided unanimously that the presence of two columns - Sampled TotalAllocations and TotalAllocations is too confusing for users. Instead, the simplest easy-to-understand solution is to keep one TotalAllocations column in Prod but make it appear as if the allocations change all at once instead of gradually due to sampling.
