### ISSUE TITLE
In Rewards page: disable "update allocations" button if no changes yet

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/df-web#455]
When I go to the "rewards" page, I see the "Update allocations" active and if I press it without changing anything it will show a modal with an error message. Can we instead disable this button if there's no change yet?

Before pressed:
<img width="1100" alt="Screenshot 2023-01-30 at 11 59 44" src="https://user-images.githubusercontent.com/13741335/215528553-9277ed20-e7cf-422b-a2e6-a91a0a1e0102.png">

After pressed:
<img width="1101" alt="Screenshot 2023-01-30 at 11 59 35" src="https://user-images.githubusercontent.com/13741335/215528607-e9698f4b-a41c-4cb3-a0aa-46c9e7e3587f.png">

ALSO the "reset" button looks disabled, but you can actually press on it. Can we give it another style? Right now it's kind of confusing to me. 

<img width="433" alt="Screenshot 2023-02-01 at 09 08 03" src="https://user-images.githubusercontent.com/13741335/216051714-f69ae558-0828-4f3f-b10b-9725ca2e0447.png">

**Comment by KatunaNorbert** [comment]
I changed the 'Reset Allocations' button so it's primary and has the same style as the 'Update Allocations' button to resolve the disabled button confusion.
Regarding making Update Allocation button disabled when there are no changes to the allocations distribution, I suggest that we keep it as it is, here is why:
- There is a lot of logic going on on checking whether the allocation has changed to run it on every change, so I suggest keeping it only on button click
- Right now there is a popup shown if there are no changes to allocations distribution after the user clicks the button which stops the user from submitting a transaction that is not going to do any changes
- The popup actually offers more context because there is a message attached to it explaining why the update can't be executet and what needs to be done

**Comment by idiom-bytes** [comment]
@KatunaNorbert please share a picture of the updates next time so I can have an idea of the final result
