### ISSUE TITLE
[APY calc v1] Provide a simple "Estimate APY vs. Best-case APY" calculation in the OceanLockComponent.

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#612]
### Problem:
- We do not want to implement a full calculator in the FE
- We do want to show the user how much better they could do if they locked for 4 years
- We want to provide users with enough context so they feel like they are intentionally making this decision ("Try to remove foot-gun conditions")
- Provide a tooltip with clear reference to FinePrint(tm)

![image (3)](https://github.com/oceanprotocol/df-web/assets/69865342/018da259-afd0-4c21-92c8-3bed8cd84d33)

### FinePrint(tm)
1. Assuming a 4-year lock up period.
2. Assuming a weekly schedule of compounding rewards into an updated lock.
3. Assuming current: number of users, reward emissions, and other key metrics remain constant.
4. Excluding lock, claim, and any tx fees.

Final Text (and calculation until further adjustments):
```
APYs are calculated assuming an initial 4-year lock up period with a weekly schedule of compounding rewards into an updated 4-year lock. This estimate works provided current: number of users, reward emissions, and other reward parameters stay constant while excluding all tx fees.
```

### DoD:
- [ ] User chooses his lockup period via shortcuts or calendar
- [ ] User sees his estimated APY based on his decisions
- [ ] User sees the estimated Best-Case APY (4yr, compound, etc...)
- [ ] User is provided with a message that tells him "Your APY could be X amount larger if you locked for 4 years"
- [ ] Use the same information as the "Average APY calculations" to estimate this number (i.e. currentEpoch, or lastEpoch)

**Comment by KatunaNorbert** [comment]
I think the best way here would be to do our own APY calculator instead of adding more text. Most of the user would want to see their APY and see how that is changing while updating the lock params.
Instead of text saying what they should do and just lock for more time, just add a button saying 'Max APY' and automatically update inputs with max values and then update the APY metric with max value.
If we want to add more text, I propose we add that inside the docs and not overload the UI with more text.
