### ISSUE TITLE
"2x Stake" is confusing; rename it

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#615]
## Problem
The following title is misleading "2x Stake" is misleading.
It makes me think as a user that I'll receive a bonus if I lock up to these datasets.

## Solution
Rename it to something more appropriate: "Boosted".
Extracted from the language of: "effective 2x allocation boost"

![image](https://github.com/oceanprotocol/df-web/assets/69865342/6768c380-7899-4ca8-a544-bd687bd9b1df)

**Comment by KatunaNorbert** [comment]
I think the key words here are: publisher, 2x stake and allocation to own asset. Because we should have something short I propose: 'Publisher 2x stake', we can omit the allocating to own asset part because that is too long, but it's key importance to have publisher there.
If we remove publisher and display: Boosted or Effective 2x allocation boost, than I think it's going to have same outcome as '2x stake', user might think it is for everyone.
