### ISSUE TITLE
Restructure the nav bar / titles

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#629]
### Problem
There are various improvements in the DF page that we should implement.
Let's restructure the Nav Bar + Pages a bit so they are easier to follow

### DoD:
- [x] Rename veOCEAN => PASSIVE
- [x] Move `Delegate` inside of `Volume-DF` (bottom of page)
- [x] Top Nav Bar should be: [PASSIVE, VOLUME DF, CHALLENGE DF, REWARDS, ABOUT]
- [ ] 1 title + 1 sentence description of how each page works

**Comment by KatunaNorbert** [comment]
@trentmc @idiom-bytes, I'm reflecting on renaming veOCEAN to Passive. 
Renaming the link in navbar makes sens, it's going to help the user who is not familiar with the app. 
My concern is renaming the veOCEAN substream inside Passive stream to Passive, it doesn't look to good, maybe we can keep that as veOCEAN.
Also it's going to be harder now to find veOCEAN in the app.

Conclusion: rename links in navbar but keep the substream name the same for now.

**Comment by KatunaNorbert** [comment]
Regarding adding 1 title + 1 sentence on each page, I don't think it's going to work. Right now the rewards and challenge DF already have the most important information on the top in form of a Banner, I think title + description there it's unnecessary + it's going to take users focus from the banner components.

On the other hand this it's going to be useful for the veOCEAN page, so I suggest just adding it in there. Volume DF already has those.

**Comment by trentmc** [comment]
Re worry about banners I've been meaning to comment on this too. So I just did, by creating a new github issue [df-web#31](https://github.com/oceanprotocol/df-web/issues/631) "Remove 2 existing banners (DF main, 2x stake), add new banner (Challenge DF)"

I recommend we do _that_ asap, since it's simple and a quick win for DF interface.

And for the context of _this_ issue...

> [Roberto in description] 1 title + 1 sentence description of how each page works
>> [Norbert] I don't think it's going to work ... <too much information, esp because banners>

Assume we've fixed banners as above. Then we have one banner max ever, that's relevant. 

My recommendation in our mtg was just "1 sentence description of how each page works". I did _not_ recommend the title, because (imo) title is redundant with navbar.

I repeat that recommendation here. No title, just description.

**Comment by KatunaNorbert** [comment]
Good points, those are what we call banners in app, I forgot about this. What I was referring to by banner or tried to highlight are the components from the top of challenge&rewards page, that have a specific design to sum up and present the main information for the specific page. I wanted to highlight that those are designed to be on top of the page instead of having an extra description above.

What about my concerns related to veOCEAN -> PASSIVE  from the previous comment?

**Comment by trentmc** [comment]
> What about my concerns related to veOCEAN -> PASSIVE from the previous comment?

Yes, I have been working to answer that:)

> My concern is renaming the veOCEAN substream inside Passive stream to Passive, it doesn't look to [sic] good, maybe we can keep that as veOCEAN. Also it's going to be harder now to find veOCEAN in the app.
> Conclusion: rename links in navbar but keep the substream name the same for now.

If I read your proposal correctly, you mean two things.
- First, in navbar, rename "veOCEAN" --> "Passive DF"
- Second, https://df.oceandao.org/rewards page (see image below), do not remove the "veOCEAN" part. Thus it will have both "Passive Rewards" and "veOCEAN".
![chunk](https://github.com/oceanprotocol/df-web/assets/5305452/d8bf2b83-ff74-4e50-97de-e2a62651b2a3)
 
If this is what you (@KatunaNorbert ) mean, then **yes** I agree. 

---

BTW partly related is a github issue I just created: [df-web#633](https://github.com/oceanprotocol/df-web/issues/633) "3 boxes in Rewards section are useless". Should be a quick win. It complements this issue.

**Comment by KatunaNorbert** [comment]
Yeah, that's what I meant so looks like we are aligned.
